#!/usr/bin/env python3
"""Build a KDP paperback interior PDF from a book's Markdown manuscript.

    python3 books/pipeline/build.py --book <slug>                # full book
    python3 books/pipeline/build.py --book <slug> --only 03       # one chapter, fast
    python3 books/pipeline/build.py --book <slug> --pages 1,2,45  # + export page JPGs

Always runs the LaTeX toolchain with cwd = repo root, so kdp-book.cls and
the vendored fonts resolve by the plain relative paths written into them.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from book import REPO_ROOT, Book, parse_book  # noqa: E402

BOOKS_DIR = REPO_ROOT / "books"
THEME_DIR = BOOKS_DIR / "theme"

# Pandoc defensively escapes a bracket that could be misread as a LaTeX
# optional-argument opener (typically at a paragraph start) as `{[}`/`{]}`
# rather than emitting a bare `[`/`]`. Match both forms.
AUTHOR_INPUT_TEX_RE = re.compile(r"(?:\{\[\}|\[)\s*AUTHOR-INPUT:(.*?)(?:\{\]\}|\])", re.S)

DEFAULT_RIGHTS_NOTE = (
    "All rights reserved. No part of this book may be reproduced, distributed, "
    "or transmitted in any form without prior written permission from the "
    "author, except brief quotations used in critical reviews."
)
DEFAULT_AI_DISCLOSURE = (
    "This book was written with AI assistance under the author's direction, "
    "outline, and review. Every claim of personal experience is the author's own."
)
DEFAULT_ISBN_NOTE = "ISBN: [assigned at KDP publishing step]"


def resolve_book_yaml(book_arg: str) -> Path:
    direct = Path(book_arg)
    if direct.suffix == ".yaml" and direct.exists():
        return direct.resolve()
    candidate = BOOKS_DIR / book_arg / "book.yaml"
    if candidate.exists():
        return candidate.resolve()
    raise SystemExit(f"No book found for {book_arg!r} (looked for {candidate})")


def write_config_tex(book: Book, out_dir: Path, pages: int | None) -> None:
    m = book.margins(pages=pages)
    lines = [
        "% Generated by build.py. Do not edit by hand; edit book.yaml instead.",
        f"\\def\\BookTrimWidth{{{m['width_in']}in}}",
        f"\\def\\BookTrimHeight{{{m['height_in']}in}}",
        f"\\def\\BookGutter{{{m['gutter_in']}in}}",
        f"\\def\\BookOuter{{{m['outer_in']}in}}",
        f"\\def\\BookTop{{{m['top_in']}in}}",
        f"\\def\\BookBottom{{{m['bottom_in']}in}}",
    ]
    (out_dir / "config.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")


def tex_escape(s: str) -> str:
    special = {"&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_",
               "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}",
               "^": r"\textasciicircum{}"}
    return "".join(special.get(c, c) for c in s)


def pandoc_chapter(md_path: Path, out_tex: Path) -> None:
    exe = shutil.which("pandoc")
    if not exe:
        raise SystemExit("pandoc not found. Install it: apt-get install pandoc")
    result = subprocess.run(
        [exe, str(md_path), "-f", "markdown+smart", "-t", "latex",
         "--top-level-division=chapter", "-o", str(out_tex)],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        raise SystemExit(f"pandoc failed on {md_path}:\n{result.stderr}")
    tex = out_tex.read_text(encoding="utf-8")
    tex = AUTHOR_INPUT_TEX_RE.sub(lambda mo: f"\\authorinput{{{mo.group(1).strip()}}}", tex)
    out_tex.write_text(tex, encoding="utf-8")


def pandoc_backmatter(md_path: Path, out_tex: Path, title: str) -> None:
    """Back-matter sections use an unnumbered, TOC-listed chapter heading."""
    pandoc_chapter(md_path, out_tex)
    tex = out_tex.read_text(encoding="utf-8")
    tex = re.sub(r"\\chapter\{[^}]*\}", "", tex, count=1)
    header = f"\\chapter*{{{tex_escape(title)}}}\\addcontentsline{{toc}}{{chapter}}{{{tex_escape(title)}}}\n"
    out_tex.write_text(header + tex, encoding="utf-8")


def front_matter_tex(book: Book) -> str:
    meta = book.meta
    out = []
    for item in meta.get("front_matter", []):
        if item == "half_title":
            out.append(f"\\halftitlepage{{{tex_escape(book.title)}}}")
        elif item == "title_page":
            out.append(
                f"\\booktitlepage{{{tex_escape(book.title)}}}"
                f"{{{tex_escape(meta.get('subtitle', ''))}}}"
                f"{{{tex_escape(meta.get('author', ''))}}}"
            )
        elif item == "copyright":
            out.append(
                "\\copyrightpage{" + tex_escape(meta.get("author", "")) + "}"
                "{" + str(meta.get("year", "2026")) + "}"
                "{" + tex_escape(meta.get("rights_note", DEFAULT_RIGHTS_NOTE)) + "}"
                "{" + tex_escape(meta.get("ai_disclosure_text", DEFAULT_AI_DISCLOSURE)) + "}"
                "{" + tex_escape(meta.get("isbn_note", DEFAULT_ISBN_NOTE)) + "}"
            )
        elif item == "dedication" and meta.get("dedication"):
            out.append(f"\\dedicationpage{{{tex_escape(meta['dedication'])}}}")
        elif item == "toc":
            out.append("\\tableofcontents\n\\clearpage")
    return "\n".join(out)


def back_matter_tex(book: Book, out_dir: Path) -> str:
    meta = book.meta
    titles = {"acknowledgments": "Acknowledgments", "about_the_author": "About the Author"}
    out = []
    for item in meta.get("back_matter", []):
        src = book.dir / "back-matter" / f"{item}.md"
        if not src.exists():
            continue
        dst = out_dir / "chapters" / f"back-{item}.tex"
        pandoc_backmatter(src, dst, titles.get(item, item.replace("_", " ").title()))
        out.append(f"\\input{{{dst.relative_to(REPO_ROOT)}}}")
    return "\n".join(out)


def build_master(book: Book, out_dir: Path, only: str | None) -> Path:
    (out_dir / "chapters").mkdir(parents=True, exist_ok=True)

    chapter_inputs = []
    chapters = book.chapters
    if only:
        chapters = [c for c in book.chapters if c.id == only]
        if not chapters:
            raise SystemExit(f"No chapter with id {only!r} in {book.path}")

    for c in chapters:
        dst = out_dir / "chapters" / f"{c.id}.tex"
        pandoc_chapter(c.path, dst)
        chapter_inputs.append(f"\\input{{{dst.relative_to(REPO_ROOT)}}}")

    parts = [
        f"\\input{{{(out_dir / 'config.tex').relative_to(REPO_ROOT)}}}",
        "\\documentclass{kdp-book}",
        f"\\def\\booktitleshort{{{tex_escape(book.title)}}}",
        "\\begin{document}",
    ]
    if not only:
        parts.append(front_matter_tex(book))
    parts.extend(chapter_inputs)
    if not only:
        parts.append(back_matter_tex(book, out_dir))
    parts.append("\\end{document}\n")

    master = out_dir / ("only.tex" if only else "master.tex")
    master.write_text("\n".join(parts), encoding="utf-8")
    return master


def run_latexmk(master: Path) -> None:
    env = dict(os.environ)
    env["TEXINPUTS"] = f"{THEME_DIR}{os.sep}:" + env.get("TEXINPUTS", "")
    result = subprocess.run(
        ["latexmk", "-xelatex", "-interaction=nonstopmode", "-halt-on-error",
         f"-output-directory={master.parent}", str(master)],
        cwd=REPO_ROOT, env=env, capture_output=True, text=True,
    )
    if result.returncode != 0:
        tail = "\n".join(result.stdout.splitlines()[-60:])
        raise SystemExit(f"latexmk failed on {master}:\n{tail}")


def pdf_page_count(pdf: Path) -> int:
    exe = shutil.which("pdfinfo")
    if not exe:
        return -1
    out = subprocess.run([exe, str(pdf)], capture_output=True, text=True).stdout
    m = re.search(r"^Pages:\s+(\d+)", out, re.M)
    return int(m.group(1)) if m else -1


def export_pages(pdf: Path, pages: list[int], out_dir: Path) -> list[Path]:
    exe = shutil.which("pdftoppm")
    if not exe:
        raise SystemExit("pdftoppm not found (poppler-utils).")
    img_dir = out_dir / "pages"
    img_dir.mkdir(exist_ok=True)
    paths = []
    for p in pages:
        prefix = img_dir / f"page-{p:03d}"
        subprocess.run([exe, "-jpeg", "-r", "150", "-f", str(p), "-l", str(p),
                         str(pdf), str(prefix)], check=True, capture_output=True)
        produced = sorted(img_dir.glob(f"page-{p:03d}*.jpg"))
        paths.extend(produced)
    return paths


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--book", required=True, help="slug under books/, or a path to book.yaml")
    ap.add_argument("--out", default=str(REPO_ROOT / "build" / "books"))
    ap.add_argument("--only", help="build a single chapter id only, skipping front/back matter")
    ap.add_argument("--pages", help="comma-separated page numbers to export as JPG for review")
    args = ap.parse_args()

    book_yaml = resolve_book_yaml(args.book)
    book = parse_book(book_yaml)
    out_dir = Path(args.out) / book.slug
    out_dir.mkdir(parents=True, exist_ok=True)

    write_config_tex(book, out_dir, pages=None)
    master = build_master(book, out_dir, only=args.only)
    run_latexmk(master)

    pdf = master.with_suffix(".pdf")
    pages = pdf_page_count(pdf)
    lo, hi = book.target_pages
    band_note = ""
    if not args.only and pages > 0:
        from book import gutter_for_pages
        used = book.margins()["gutter_in"]
        real = gutter_for_pages(pages)
        if abs(used - real) > 1e-9:
            band_note = (f"  [gutter was set for the {lo}-{hi} target band; actual "
                         f"page count {pages} wants {real}in, not {used}in — rebuild "
                         f"after content settles]")

    print(f"\n  {book.title!r}  ->  {pdf.relative_to(REPO_ROOT)}")
    print(f"  {pages} page(s)  (target {lo}-{hi}){band_note}")

    if args.pages:
        wanted = [int(p) for p in args.pages.split(",")]
        imgs = export_pages(pdf, wanted, out_dir)
        print("  exported for review:")
        for p in imgs:
            print(f"    {p}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
